exclude: ['Rakefile', 'config.rb', 'CNAME', 'README.md', 'CHANGELOG.md', 'JEKYLL-WIKI.taskpaper', 'JEKYLL-WIKI.sublime-project', 'JEKYLL-WIKI.sublime-workspace']

markdown: rdiscount
pygments: true
permalink: /:categories/:year/:month/:day/:title